logging:
  level:
    com.aric.samples: TRACE
server:
  port: 8082
spring:
  cloud:
    config:
      server:
        jdbc:
          sql: select SETTING, VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
          order: 1
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.0.0.197:1433;database=heartbeat
    username: heartbeat
    password: heartbeat
  profiles:
    active:
    - jdbc
  jpa:
    show-sql: true

